// Timezone aliases — tz abbreviations plus city nicknames. Mirrors
// `TIMEZONE_ALIASES` in lib/tztr.rb. Ruby's hash lets a later key overwrite an
// earlier one; only `gmt` is duplicated there (UTC, then Europe/London), so the
// effective value Europe/London is what appears here.

/// All timezone aliases as `(alias, IANA name)` pairs, sorted by alias.
pub fn timezone_aliases() -> &'static [(&'static str, &'static str)] {
    &[
        ("akdt", "America/Anchorage"),
        ("akst", "America/Anchorage"),
        ("alaska", "America/Anchorage"),
        ("amsterdam", "Europe/Amsterdam"),
        ("anchorage", "America/Anchorage"),
        ("auckland", "Pacific/Auckland"),
        ("aedt", "Australia/Sydney"),
        ("aest", "Australia/Sydney"),
        ("beijing", "Asia/Shanghai"),
        ("berlin", "Europe/Berlin"),
        ("boston", "America/New_York"),
        ("bst", "Europe/London"),
        ("central", "America/Chicago"),
        ("cest", "Europe/Berlin"),
        ("cet", "Europe/Berlin"),
        ("chicago", "America/Chicago"),
        ("cdt", "America/Chicago"),
        ("cst", "America/Chicago"),
        ("cst_china", "Asia/Shanghai"),
        ("ct", "America/Chicago"),
        ("delhi", "Asia/Kolkata"),
        ("denver", "America/Denver"),
        ("dubai", "Asia/Dubai"),
        ("eastern", "America/New_York"),
        ("edt", "America/New_York"),
        ("est", "America/New_York"),
        ("et", "America/New_York"),
        ("gmt", "Europe/London"),
        ("hawaii", "Pacific/Honolulu"),
        ("hkt", "Asia/Hong_Kong"),
        ("hong_kong", "Asia/Hong_Kong"),
        ("hongkong", "Asia/Hong_Kong"),
        ("honolulu", "Pacific/Honolulu"),
        ("hst", "Pacific/Honolulu"),
        ("ist", "Asia/Kolkata"),
        ("jst", "Asia/Tokyo"),
        ("kst", "Asia/Seoul"),
        ("la", "America/Los_Angeles"),
        ("london", "Europe/London"),
        ("miami", "America/New_York"),
        ("mountain", "America/Denver"),
        ("mdt", "America/Denver"),
        ("mst", "America/Denver"),
        ("mt", "America/Denver"),
        ("mumbai", "Asia/Kolkata"),
        ("nyc", "America/New_York"),
        ("nzdt", "Pacific/Auckland"),
        ("nzst", "Pacific/Auckland"),
        ("pacific", "America/Los_Angeles"),
        ("paris", "Europe/Paris"),
        ("pdt", "America/Los_Angeles"),
        ("pst", "America/Los_Angeles"),
        ("pt", "America/Los_Angeles"),
        ("sao_paulo", "America/Sao_Paulo"),
        ("seattle", "America/Los_Angeles"),
        ("seoul", "Asia/Seoul"),
        ("sf", "America/Los_Angeles"),
        ("shanghai", "Asia/Shanghai"),
        ("singapore", "Asia/Singapore"),
        ("sydney", "Australia/Sydney"),
        ("tokyo", "Asia/Tokyo"),
        ("toronto", "America/Toronto"),
        ("utc", "UTC"),
        ("vancouver", "America/Vancouver"),
        ("z", "UTC"),
    ]
}
